@startuml
'https://plantuml.com/sequence-diagram
Main -> Game: new()
Game -> ArrayList: new()
Game -> TextUI: new()
Game -> FileIO: new()
Main -> Game: setup()
Game -> TextUI: displayMsg()
Game -> FileIO: readData(path)
FileIO --> Game: ArrayList data
alt data not empty && continue saved game
loop for each s in data
Game -> Game: createPlayer(name, balance)
Game -> Player: new(name, balance)
end
else
Game -> Game: registerPlayers()
end
@enduml

